{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rlhf-ppo.serviceAccountName" . }}
  labels:
    {{- include "rlhf-ppo.labels" . | nindent 4 }}
{{- end }}
