"""Unit tests for the Pydantic data schemas."""

from __future__ import annotations

from uuid import UUID

import pytest
from pydantic import ValidationError

from rlhf.data.schemas import PPOBatch, Preference, Prompt, Rollout


def _valid_rollout(length: int = 3) -> Rollout:
    return Rollout(
        prompt_ids=[1, 2],
        response_ids=list(range(length)),
        logprobs=[-0.1] * length,
        ref_logprobs=[-0.2] * length,
        values=[0.5] * length,
        reward=1.0,
    )


@pytest.mark.parametrize("field", ["chosen", "rejected", "prompt"])
def test_preference_rejects_empty_text(field: str) -> None:
    kwargs = {
        "prompt": "p",
        "chosen": "c",
        "rejected": "r",
        "annotator_id": "a1",
        field: "   ",
    }
    with pytest.raises(ValidationError):
        Preference(**kwargs)


def test_preference_uuid_autogenerated() -> None:
    pref = Preference(prompt="p", chosen="c", rejected="r", annotator_id="a")
    assert isinstance(pref.id, UUID)
    assert pref.id.version == 4
    # Two preferences get distinct ids.
    other = Preference(prompt="p", chosen="c", rejected="r", annotator_id="a")
    assert pref.id != other.id


def test_rollout_rejects_misaligned_lengths() -> None:
    with pytest.raises(ValidationError):
        Rollout(
            prompt_ids=[1],
            response_ids=[1, 2, 3],
            logprobs=[-0.1, -0.1],  # length 2 != 3
            ref_logprobs=[-0.2, -0.2, -0.2],
            values=[0.5, 0.5, 0.5],
            reward=1.0,
        )


def test_rollout_optional_arrays_must_align_when_present() -> None:
    with pytest.raises(ValidationError):
        Rollout(
            prompt_ids=[1],
            response_ids=[1, 2, 3],
            logprobs=[-0.1, -0.1, -0.1],
            ref_logprobs=[-0.2, -0.2, -0.2],
            values=[0.5, 0.5, 0.5],
            reward=1.0,
            advantages=[0.1, 0.2],  # wrong length
        )


def test_rollout_response_length_property() -> None:
    assert _valid_rollout(length=5).response_length == 5


@pytest.mark.parametrize(
    "model_factory",
    [
        lambda: Preference(prompt="p", chosen="c", rejected="r", annotator_id="a"),
        _valid_rollout,
        lambda: Prompt(text="hello"),
        lambda: PPOBatch(rollouts=[_valid_rollout()], stats={"loss": 1.0}),
    ],
)
def test_round_trip_serialization_is_identity(model_factory) -> None:  # type: ignore[no-untyped-def]
    model = model_factory()
    restored = type(model)(**model.model_dump())
    assert restored == model


def test_prompt_rejects_empty_text() -> None:
    with pytest.raises(ValidationError):
        Prompt(text="")


def test_ppo_batch_len() -> None:
    batch = PPOBatch(rollouts=[_valid_rollout(), _valid_rollout()])
    assert len(batch) == 2
